---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - sudo ansible --version
  - sudo ansible-galaxy install --roles-path=./tests/roles rahul0705.rtorrent
  - sudo ansible-galaxy install --roles-path=./tests/roles rahul0705.apache

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Test for Syntax
  - >
    sudo ansible-playbook -i tests/inventory tests/test.yml
    --syntax-check
  # Test for Failure
  - >
    sudo ansible-playbook -i tests/inventory tests/test.yml
    --connection=local
  # Test for Idempotence
  - >
    sudo ansible-playbook -i tests/inventory tests/test.yml
    --connection=local
    | grep -q 'changed=0.*failed=0'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
