---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version
  - ansible-galaxy install --roles-path=./tests/roles rahul0705.rtorrent
  - ansible-galaxy install --roles-path=./tests/roles rahul0705.apache
  - ansible-galaxy install --roles-path=./tests/roles rahul0705.certbot

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Test for Syntax
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --syntax-check
  # Test for Failure
  - >
    ansible-playbook -i tests/inventory tests/test.yml --become
    --connection=local
  # Test for Idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml --become
    --connection=local
    | grep -q 'changed=0.*failed=0'
  # Test for Success
  - >
    curl -s --user rutorrent:rutorrent 127.0.0.1 | grep -q 'rTorrent'
  - >
    sudo ufw status | grep -q "80.*ALLOW.*Anywhere"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
