---
# tasks file for ansible-rutorrent

- name: "Debian | install dependacy"
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apache2
    - php5
    - libapache2-mod-scgi
    - curl
    - gzip
    - unzip
    - unrar
    - mediainfo
  when:
    ansible_os_family: 'Debian'
  tags:
    dependacy

- name: "All | add rtorrent user to apache group"
  sudo: yes
  user:
    name: "{{ rtorrent_user }}"
    groups: www-data
    append: yes
  tags:
    dependacy

- name: "All | enable apache modules"
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - scgi
  notify:
    - restart apache
  tags:
    dependacy

- name: "All | enable apache ssl modules"
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - ssl
  notify:
    - restart apache
  when:
    - rutorrent_ssl_set
  tags:
    dependacy

- name: "All | download rutorrent"
  sudo: yes
  get_url:
    url: "{{ rutorrent_download_url }}"
    dest: "{{ rutorrent_download_dest }}"
  tags:
    install

- name: "All | download rutorrent plugins"
  sudo: yes
  get_url:
    url: "{{ rutorrent_plugins_download_url }}"
    dest: "{{ rutorrent_plugins_download_dest }}"
  tags:
    install

- name: "All | create rutorrent directory"
  sudo: yes
  file:
    path: "{{ rutorrent_document_root }}"
    state: directory
    owner: www-data
    group: www-data
  tags:
    install

- name: "All | install rutorrent"
  sudo: yes
  unarchive:
    src: "{{ rutorrent_download_dest }}"
    dest: "{{ rutorrent_www_dir }}"
    copy: no
    creates: "{{ rutorrent_document_root }}/conf"
    owner: www-data
    group: www-data
  tags:
    install

- name: "All | install rutorrent plugins"
  sudo: yes
  unarchive:
    src: "{{ rutorrent_plugins_download_dest }}"
    dest: "{{ rutorrent_document_root }}"
    copy: no
    creates: "{{ rutorrent_document_root }}/plugins/unpack"
    owner: www-data
    group: www-data
  tags:
    install

- name: "All | configure rutorrent apache site"
  sudo: yes
  template:
    src: rtorrent.conf.j2
    dest: /etc/apache2/sites-available/rtorrent.conf
    owner: www-data
    group: www-data
  notify:
    - restart apache
  tags:
    configure

- name: "All | configure rutorrent htaccess file"
  sudo: yes
  template:
    src: htaccess.j2
    dest: "{{ rutorrent_document_root }}/.htaccess"
  notify:
    - restart apache
  tags:
    configure

- name: "All | create rutorrent ssl key folders"
  sudo: yes
  file:
    path: "{{ rutorrent_ssl_certificate_path }}"
    state: directory
  notify:
    - restart apache
  when:
    - rutorrent_ssl_set
  tags:
    configure

- name: "All | configure rutorrent ssl site"
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  with_items:
    - { src: "rtorrent.crt.j2", dest: "{{ rutorrent_ssl_certificate_file }}" }
    - { src: "rtorrent.key.j2", dest: "{{ rutorrent_ssl_certificate_key_file }}" }
    - { src: "rtorrent.pem.j2", dest: "{{ rutorrent_ssl_certificate_chain_file }}" }
    - { src: "rtorrent.pem.j2", dest: "{{ rutorrent_ssl_ca_certificate_file }}" }
  notify:
    - restart apache
  when:
    - rutorrent_ssl_set
  tags:
    configure

- name: "All | enable rutorrent apache site"
  sudo: yes
  file:
    src: /etc/apache2/sites-available/rtorrent.conf
    dest: /etc/apache2/sites-enabled/rtorrent.conf
    state: link
  notify:
    - restart apache
  tags:
    configure

- name: "All | configure rutorrent"
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  with_items:
    - { src: "access.ini.j2", dest: "{{ rutorrent_document_root }}/conf/access.ini" }
    - { src: "config.php.j2", dest: "{{ rutorrent_document_root }}/conf/config.php" }
    - { src: "plugins.ini.j2", dest: "{{ rutorrent_document_root }}/conf/plugins.ini" }
  tags:
    configure
