---
# tasks file for ansible-rutorrent

- name: "install ansible dependencies"
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - python-passlib
  when:
    - rutorrent_create_htpasswd
  tags:
    dependacy

- name: "install rutorrent dependencies"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gzip
    - unzip
    - unrar
    - mediainfo
    - ffmpeg
  tags:
    dependacy

- name: "add rtorrent user to apache group"
  user:
    name: "{{ rtorrent_user }}"
    groups: www-data
    append: yes
  tags:
    dependacy

- name: "unpack source into rutorrent directory"
  unarchive:
    src: "{{ rutorrent_download_url }}"
    dest: "{{ rutorrent_www_dir }}"
    copy: no
    creates: "{{ rutorrent_document_root }}"
    group: www-data
    mode: g+w
  tags:
    install

- name: "rename unpacked folder"
command: mv {{ rutorrent_www_dir }}/ruTorrent-master {{ rutorrent_document_root }}
args:
  creates: "{{ rutorrent_document_root }}"
tags:
  - install

- name: "configure rutorrent apache site"
  template:
    src: rtorrent.conf.j2
    dest: /etc/apache2/sites-available/rtorrent.conf
    group: www-data
  notify:
    - restart apache
  tags:
    configure

- name: "create htpasswd file with rutorrent user"
  htpasswd:
    path: "{{ rutorrent_document_root }}/.htpasswd"
    name: "{{ rutorrent_user }}"
    password: "{{ rutorrent_password }}"
    group: www-data
  notify:
    - restart apache
  when:
    - rutorrent_create_htpasswd
  tags: configure

- name: "allow http rutorrent in ufw"
  become: yes
  ufw:
    rule: allow
    port: "{{ rutorrent_http_port }}"
    state: enabled
  when:
    - rutorrent_configure_ufw
  tags:
    - firewall

- name: "create rutorrent ssl key folders"
  file:
    path: "{{ rutorrent_ssl_certificate_path }}"
    state: directory
  notify:
    - restart apache
  when:
    - rutorrent_ssl_set
  tags:
    configure

- name: "create rutorrent ssl certs"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: www-data
  with_items:
    - { src: "rtorrent.crt", dest: "{{ rutorrent_ssl_certificate_file }}" }
    - { src: "rtorrent.key", dest: "{{ rutorrent_ssl_certificate_key_file }}" }
    - { src: "rtorrent.pem", dest: "{{ rutorrent_ssl_certificate_chain_file }}" }
    - { src: "rtorrent.pem", dest: "{{ rutorrent_ssl_ca_certificate_file }}" }
  notify:
    - restart apache
  when:
    - rutorrent_ssl_set
  tags:
    configure

- name: "allow https rutorrent in ufw"
  become: yes
  ufw:
    rule: allow
    port: "{{ rutorrent_http_port }}"
    state: enabled
  when:
    - rutorrent_configure_ufw
    - rutorrent_ssl_set
  tags:
    - firewall

- name: "enable rutorrent apache site"
  file:
    src: /etc/apache2/sites-available/rtorrent.conf
    dest: /etc/apache2/sites-enabled/rtorrent.conf
    state: link
  notify:
    - restart apache
  tags:
    configure

- name: "configure rutorrent"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: www-data
    mode: g+w
  with_items:
    - { src: "access.ini.j2", dest: "{{ rutorrent_document_root }}/conf/access.ini" }
    - { src: "config.php.j2", dest: "{{ rutorrent_document_root }}/conf/config.php" }
    - { src: "plugins.ini.j2", dest: "{{ rutorrent_document_root }}/conf/plugins.ini" }
  tags:
    configure
