---
# tasks file for ansible-rutorrent

- name: Install ansible dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - python-passlib
  when:
    - rutorrent_create_htpasswd
  tags:
    dependacy

- name: Add additional repos to the package manager
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
      skip: true
  tags:
    - dependancy

- name: Install rutorrent dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gzip
    - unzip
    - unrar
    - mediainfo
    - ffmpeg
  tags:
    dependacy

- name: Add rtorrent user to apache group
  user:
    name: "{{ rtorrent_user }}"
    groups: www-data
    append: yes
  tags:
    dependacy

- name: Unpack source into rutorrent directory
  unarchive:
    src: "{{ rutorrent_download_url }}"
    dest: "{{ rutorrent_www_dir }}"
    copy: no
    creates: "{{ rutorrent_document_root }}"
    group: www-data
    mode: g+w
  tags:
    install

- name: Rename unpacked folder
  command: mv {{ rutorrent_www_dir }}/ruTorrent-{{ rutorrent_version }} {{ rutorrent_document_root }}
  args:
    creates: "{{ rutorrent_document_root }}"
  tags:
    - install

- name: Configure rutorrent apache site
  template:
    src: rtorrent.conf.j2
    dest: /etc/apache2/sites-available/rtorrent.conf
    group: www-data
  notify:
    - Restart apache
  tags:
    configure

- name: Create htpasswd file with rutorrent user
  htpasswd:
    path: "{{ rutorrent_document_root }}/.htpasswd"
    name: "{{ rutorrent_user }}"
    password: "{{ rutorrent_password }}"
    group: www-data
  notify:
    - Restart apache
  when:
    - rutorrent_create_htpasswd
  tags: configure

- name: Allow http rutorrent in ufw
  become: yes
  ufw:
    rule: allow
    port: "{{ rutorrent_http_port }}"
    state: enabled
  when:
    - rutorrent_configure_ufw
  tags:
    - firewall

- name: Allow https rutorrent in ufw
  become: yes
  ufw:
    rule: allow
    port: "{{ rutorrent_https_port }}"
    state: enabled
  when:
    - rutorrent_configure_ufw
    - rutorrent_ssl_set
  tags:
    - firewall

- name: Enable rutorrent apache site
  file:
    src: /etc/apache2/sites-available/rtorrent.conf
    dest: /etc/apache2/sites-enabled/rtorrent.conf
    state: link
  notify:
    - Restart apache
  tags:
    configure

- name: Configure rutorrent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: www-data
    mode: g+w
  with_items:
    - { src: "access.ini.j2", dest: "{{ rutorrent_document_root }}/conf/access.ini" }
    - { src: "config.php.j2", dest: "{{ rutorrent_document_root }}/conf/config.php" }
    - { src: "plugins.ini.j2", dest: "{{ rutorrent_document_root }}/conf/plugins.ini" }
  tags:
    configure
