---
# tasks file for ansible-rutorrent

- name: "install dependencies"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gzip
    - unzip
    - unrar
    - mediainfo
    - ffmpeg
  tags:
    dependacy

- name: "add rtorrent user to apache group"
  user:
    name: "{{ rtorrent_user }}"
    groups: www-data
    append: yes
  tags:
    dependacy

- name: "unpack source into rutorrent directory"
  unarchive:
    src: "{{ rutorrent_download_url }}"
    dest: "{{ rutorrent_www_dir }}"
    copy: no
    creates: "{{ rutorrent_document_root }}"
    owner: www-data
    group: www-data
  tags:
    install

- name: "configure rutorrent apache site"
  template:
    src: rtorrent.conf.j2
    dest: /etc/apache2/sites-available/rtorrent.conf
    owner: www-data
    group: www-data
  notify:
    - restart apache
  tags:
    configure

- name: "configure rutorrent htaccess file"
  template:
    src: htaccess.j2
    dest: "{{ rutorrent_document_root }}/.htaccess"
  notify:
    - restart apache
  tags:
    configure

- name: "create rutorrent ssl key folders"
  file:
    path: "{{ rutorrent_ssl_certificate_path }}"
    state: directory
  notify:
    - restart apache
  when:
    - rutorrent_ssl_set
  tags:
    configure

- name: "configure rutorrent ssl site"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  with_items:
    - { src: "rtorrent.crt.j2", dest: "{{ rutorrent_ssl_certificate_file }}" }
    - { src: "rtorrent.key.j2", dest: "{{ rutorrent_ssl_certificate_key_file }}" }
    - { src: "rtorrent.pem.j2", dest: "{{ rutorrent_ssl_certificate_chain_file }}" }
    - { src: "rtorrent.pem.j2", dest: "{{ rutorrent_ssl_ca_certificate_file }}" }
  notify:
    - restart apache
  when:
    - rutorrent_ssl_set
  tags:
    configure

- name: "enable rutorrent apache site"
  file:
    src: /etc/apache2/sites-available/rtorrent.conf
    dest: /etc/apache2/sites-enabled/rtorrent.conf
    state: link
  notify:
    - restart apache
  tags:
    configure

- name: "configure rutorrent"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  with_items:
    - { src: "access.ini.j2", dest: "{{ rutorrent_document_root }}/conf/access.ini" }
    - { src: "config.php.j2", dest: "{{ rutorrent_document_root }}/conf/config.php" }
    - { src: "plugins.ini.j2", dest: "{{ rutorrent_document_root }}/conf/plugins.ini" }
  tags:
    configure
